### ISSUE TITLE
Font-position when starting point rotate? 

### ISSUE THREAD

**Issue by clarklight** [kimmobrunfeldt/progressbar.js#70]
Hi!! First just want to say this progessBar is amazing!! 

I just have a quick question

 Starting-point, i see that in another threat you gave a fiddle example(for rotation), but i see that the text is also rotated, wondering if in the future you have a plan to allow user to change the rotate but keep the text rotation fixed. 

I tried to rotate the container, then force the .progress-text rotate 180 degrees, but then the text(numbers) loses its position. http://jsfiddle.net/1s6149mk/2/
Thanks!!

**Comment by clarklight** [comment]
Don't worry, i fixed it. But for the percentage(the number), have to do !important to force the .progress-text to accept the new CSS class. Then can mess about with the position. http://jsfiddle.net/1s6149mk/3/

**Comment by kimmobrunfeldt** [comment]
Instead of applying rotation to container, apply the rotation just for the SVG element:
```css
#container {
   left:32%;
    width: 40%;
    height: 40%;
    font-size:280%;
}
#container > svg {
    transform: rotate(180deg);
}
```
