### ISSUE TITLE
Start at 3 o'clock

### ISSUE THREAD

**Issue by furyscript** [kimmobrunfeldt/progressbar.js#96]
Actually it start at twelve o'clock. I want to start bar from three o'clock

Now:
```
        Start
-                   -
          .
```
After I want
```
         .
-                start
         .
```
The direction is correct

**Comment by kimmobrunfeldt** [comment]
The easiest way to achieve this is to apply transform to the SVG element: http://jsfiddle.net/zv2pu0ks/2/. If you apply the transform to the container, also text will be rotated.

Note: you might need browser prefixes in CSS.

**HTML:**
```html
<div id="container"></div>
```
**CSS:**
```css
#container {
    width: 100px;
    height: 100px;
}

#container > svg {
    width: 100%;
    display: block;
    transform: rotate(90deg);
}
```

**JS:**
```js
var circle = new ProgressBar.Circle('#container', {
    color: '#FCB03C',
    text: {
        value: 'test'
    }
});

circle.animate(1.0);  // Number from 0.0 to 1.0
```

Other way to achieve this would be to write new [circle.js](https://github.com/kimmobrunfeldt/progressbar.js/blob/master/src/circle.js) where the drawing is started from the point you want.
